/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as CreateIndexImport } from "./routes/create/index"
import { Route as TimerIdIndexImport } from "./routes/$timerId/index"
import { Route as TimerIdEditImport } from "./routes/$timerId/edit"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const CreateIndexRoute = CreateIndexImport.update({
  id: "/create/",
  path: "/create/",
  getParentRoute: () => rootRoute,
} as any)

const TimerIdIndexRoute = TimerIdIndexImport.update({
  id: "/$timerId/",
  path: "/$timerId/",
  getParentRoute: () => rootRoute,
} as any)

const TimerIdEditRoute = TimerIdEditImport.update({
  id: "/$timerId/edit",
  path: "/$timerId/edit",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/$timerId/edit": {
      id: "/$timerId/edit"
      path: "/$timerId/edit"
      fullPath: "/$timerId/edit"
      preLoaderRoute: typeof TimerIdEditImport
      parentRoute: typeof rootRoute
    }
    "/$timerId/": {
      id: "/$timerId/"
      path: "/$timerId"
      fullPath: "/$timerId"
      preLoaderRoute: typeof TimerIdIndexImport
      parentRoute: typeof rootRoute
    }
    "/create/": {
      id: "/create/"
      path: "/create"
      fullPath: "/create"
      preLoaderRoute: typeof CreateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$timerId/edit": typeof TimerIdEditRoute
  "/$timerId": typeof TimerIdIndexRoute
  "/create": typeof CreateIndexRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$timerId/edit": typeof TimerIdEditRoute
  "/$timerId": typeof TimerIdIndexRoute
  "/create": typeof CreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/$timerId/edit": typeof TimerIdEditRoute
  "/$timerId/": typeof TimerIdIndexRoute
  "/create/": typeof CreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/$timerId/edit" | "/$timerId" | "/create"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/$timerId/edit" | "/$timerId" | "/create"
  id: "__root__" | "/" | "/$timerId/edit" | "/$timerId/" | "/create/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimerIdEditRoute: typeof TimerIdEditRoute
  TimerIdIndexRoute: typeof TimerIdIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimerIdEditRoute: TimerIdEditRoute,
  TimerIdIndexRoute: TimerIdIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$timerId/edit",
        "/$timerId/",
        "/create/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$timerId/edit": {
      "filePath": "$timerId/edit.tsx"
    },
    "/$timerId/": {
      "filePath": "$timerId/index.tsx"
    },
    "/create/": {
      "filePath": "create/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
